language: python
python:
#  - "2.6"      Incomplete unittest module
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
#  - "pypy"     Can't install lxml
#  - "pypy3"    Can't install lxml
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: nosetests