site_name: Livescrape documentation
repo_url: https://github.com/ondergetekende/livesscrape
pages:
    - 'Introduction': 'index.md'
    - 'Tutorial': 'tutorial.md'
    - 'API documentation': 'api.md'
    - 'Advanced document retrieval': 'advanced.md'


